### ISSUE TITLE
Performance Issue: Larger then 256 Sizes

### ISSUE THREAD

**Issue by eumario** [spimort/TerraBrush#1]
When attempting to edit Terrain larger then 256, editor slows down when attempting to modify terrain.

**Comment by spimort** [comment]
Thanks for posting this!

For my own project, having a big map was not a requirement that's why there is no LOD at the moment. I'll check if I can add the support of something like clipmaps (probably after the holidays).

**Comment by spimort** [comment]
@eumario 
That should be better with the new clipmap feature merged into main.
Let me know if it helps, I'll close the issue after. 🙂

**Comment by eumario** [comment]
@spimort This looks good.  Able to create a terrain 4500m Squared, with no issues.

**Comment by spimort** [comment]
Awesome, I'll close the issue then!

Thank you @eumario for taking the time to test it 🙂
