### ISSUE TITLE
Error when having more than 4 textures

### ISSUE THREAD

**Issue by EmineBS** [spimort/TerraBrush#114]
When I add more than 4 textures I get this error and the map becomes invisible, I also found that a new empty Splatmap is created and added to the splatmaps array and when I delete it the main map appears again and everything works fine, so how to add more textures without facing this problem again ?
![Capture](https://github.com/spimort/TerraBrush/assets/65482080/372f08ab-3364-46f6-8535-b881f72f2fa3)

**Comment by spimort** [comment]
Hey @EmineBS !

In your fifth textureset, make sure you provide the same kind of textures you do for the others.
Meaning that you need to provide at least the albedo. If in the others you provided a normal map, you need to provide one as well. If you provided a roughness texture, you need to provide one as well for the new one. And so on.

Can you confirm me everything as been set this way? 🙂

**Comment by EmineBS** [comment]
Yes I placed all the textures correctly, even when I try to assign the same texture from textureSet 4 to textureSet 5, the error appears again and a new empty Splatmap is added and I can't delete it only when I delete textureSet 5.

**Comment by spimort** [comment]
Alright, would you be able to share the project with me? I could check what is happening 🙂

**Comment by spimort** [comment]
Any news on that @EmineBS ?

**Comment by Schwagsone** [comment]
![image](https://github.com/spimort/TerraBrush/assets/116524236/affc7fb1-eea2-4f04-974c-400435473722)
Check the settings on all of them. Godot is weird.

**Comment by EmineBS** [comment]
Solved! Yes, all imported textures must be on the same import settings, even if there is any small thing different from others, this error will appear

**Comment by spimort** [comment]
Alright thanks @EmineBS for the info about the defaults 🙂
