### ISSUE TITLE
How to optimize performance

### ISSUE THREAD

**Issue by DriftWare07** [spimort/TerraBrush#12]
The title pretty much says it all. What values do i need to adjust? It runs just fine in editor, but when the project compiles, i get a giant spike of lag that usually lasts for a second or more every time i turn the camera or move around.

**Comment by DriftWare07** [comment]
I have learned a valuable lesson: DO NOT TRY TO RENDER 4K TEXTURES ON ABSOLUTELY EVERYTHING.

**Comment by spimort** [comment]
haha, all go, so, should I close this issue for now?
