### ISSUE TITLE
Error when enabling!

### ISSUE THREAD

**Issue by MountainLabsYT** [spimort/TerraBrush#120]
Godot version: v4.2.2 stable mono

installing the plugin works as normal, no problems.
enabling the plugin gives this error:
Unable to load addon script from path: 'res://addons/terrabrush/Plugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/terrabrush/plugin.cfg' to prevent further errors.

No idea whats wrong or why, but I have always had this problem and have never been able to get it to work.

**Comment by spimort** [comment]
Hey @Derpysphere !

Make sure you compile the project before enabling the addon (using the hammer button) 🙂
Take a look at the video here (timestamp included) : https://youtu.be/dD65GIrJFMI?t=120

**Comment by spimort** [comment]
@MountainLabsYT I'll close the issue for now, feel free to open a new one if you have other issues! 🙂
