### ISSUE TITLE
water shader work around

### ISSUE THREAD

**Issue by MachinistJohn** [spimort/TerraBrush#128]
not an issue just an idea. why not query the engine for its version number and have two separate shaders. then just load the one for the corresponding godot version. that way you can support everyone in one addon.
<code>
func get_godot_version():
    var version = Engine.get_version_info()
    print("Godot version: %s.%s.%s" % [version.major, version.minor, version.patch]) 
    # If you want to include the status (e.g., beta, rc)
    if version.status:
        print("Status: ", version.status)
/<code>

**Comment by spimort** [comment]
That's a great idea!
I'll try to work on that 🙂

**Comment by spimort** [comment]
This as been done with https://github.com/spimort/TerraBrush/pull/131

Thanks for the suggestion!
