### ISSUE TITLE
Anti-Tile is unable to be turned off

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#13]
Unable to turn Anti-Tile off. I'm using a more 2.5D pixel style texture set, which looks terrible when painted at random angles! This will also make 2D style cliffs look even worse.
[preview](https://github.com/spimort/TerraBrush/assets/157936534/2ff714cc-4ea6-41a5-93f4-a79a13a2d725)

**Comment by spimort** [comment]
This feature has been added in the main branch

**Comment by Ika-BakaKu** [comment]
OMG thank you so much, this is game changing! You rock!
