### ISSUE TITLE
Can i make placing trees faster ?

### ISSUE THREAD

**Issue by Reishi-png** [spimort/TerraBrush#132]
my trees are loading very long on object placing tool. What can i do to make that faster ? if possible 

my trees are 2000 polys each

#enhancment can you add grass fading in beetwen states if possible

**Comment by spimort** [comment]
I think the objects placement could be improved. Some experiments will have to be done.

**Comment by spimort** [comment]
It should be better now with the version 0.9.0Alpha.
You have two choices, to use packed scene (like before but with more perfs) or to use the new octree multimeshes thing 🙂

I'll close the issue for now, feel free to open a new one if neede
