### ISSUE TITLE
Support for non .net version of Godot ?

### ISSUE THREAD

**Issue by saminton** [spimort/TerraBrush#14]
I don't know how feasible this is but is there any chance of a non .net version ?

**Comment by spimort** [comment]
Hey @saminton !
Right now the addon only works with .net but you will be able to continue using GDscript or GDextensions flawlessly 🙂

The only thing to do is to use the .net version of Godot, nothing more is required.

Not impossible that it would change in the future but right now this is how I created the addon.

**Comment by spimort** [comment]
I'll close this issue for now since rebuilding it with GDScript or GDExtension would require a lot of stuff

**Comment by spimort** [comment]
Just in case, this is now a GDExtension, written in c++ 🙂
