### ISSUE TITLE
When rebuilding Terrain Editor docker for terrain tools resets it's position to where it starts on first use.

### ISSUE THREAD

**Issue by GeminiSquishGames** [spimort/TerraBrush#140]
I can't seem to get the terrain editor docker to stay where I want it after I rebuild the terrain. It saves it's position in my custom layout so it will go back when I select my layout, but it always pops back to where it started default when I rebuild the terrain. Is there something I'm missing or would that be a bug? This is with Godot 4.3, on windows 10, with an NVidia RTX 2060.

**Comment by spimort** [comment]
Oh that's interesting!
I never realized we could move the tab haha!

I might have something to do to handle this!

I'll check that!

**Comment by spimort** [comment]
@GeminiSquishGames After some tests, It seems like if I want to support this, I'll have to add this panel always open, even if no Terrain node is selected.

![image](https://github.com/user-attachments/assets/e4c1c087-24b3-4e7b-bfe0-39e71a47e1d0)

I don't know yet if I like that or not! I'm still thinking about this.
I love the fact that we can move the panel, but I hate the fact that it's always there, as soon as the plugin is enabled 🫤

**Comment by GeminiSquishGames** [comment]
Hmm, I see what you mean. You could do the add_control_to_bottom_panel instead of using docks for your controls. That's where the Visual Shader node editor and Animation editor are by default, I don't remember the conversion from GDscript to C# for editor tools off the top of my head, but you should also be able to put the dock anywhere with the right CONSTANT position iirc. I think docks are just always open, it's like that for the Git version control plugin too. It just always exists if the plugin is active and becomes active when it's created. I have to close plugin docks if I don't need them or tuck them somewhere else in my personal layout.

**Comment by spimort** [comment]
The thing is, if I put it at the bottom, you won't be able to move it, it will have to remain there, since it's not a "dock".🫤
I think at this point, I'll have to decide if I want to have the empty panel or not.
It's not too bad I think but yeah!

Also, I already use the _handles, it does nothing for this 😟

I made a pull request here, in case you want to try it : https://github.com/spimort/TerraBrush/pull/141

**Comment by GeminiSquishGames** [comment]
It doesn't have to be empty maybe? You could have it have one ui scene to
handle instancing the terrain node and other pre-settings, perhaps.  The
file system dock can go either way now since 4.3, dock or bottom, but I do
not know what that method is or if it is exposed to the EditorPlugin class
ATM.

It not being a dock would be why you'd put it at the bottom, it wouldn't
need to be moved as the other docks wouldn't be in it's way or vice versa,
and I doubt that I would need to use any other bottom panel things when
editing the terrain, but I probably would use docks like the inspector and
node hierarchy.

Either way works as long as it doesn't move from where the user wants it
when they rebuild the terrain, which is often. 😓 Thank you so much for
looking into it though!

**Comment by spimort** [comment]
Sounds good! I think that what I could do is to add a setting for it, so it can be turned on/off.
The setting would be to keep the dock alive or not.
And probably defaulted to true.

It will break how people use it right now but I think it's for the best. And they could turn it off if needed.

I'll try that probably this week.

**Comment by spimort** [comment]
I did push the modification to main 🙂 I'll close the issue for now, if you have other problems with it, feel free to open another one!

**Comment by spimort** [comment]
In version 0.8.6Alpha
