### ISSUE TITLE
Graphical glitch with snow, when none exists

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#15]
During serval terrain creations so far, I noticed an odd bug that hits randomly when moving my player node. I took a video showcasing the bug and how it can easily be resolved with no issues, but how confusing it can be when you think your accidently moving your maps.

Before I added a sand terrain to snow, it would move the entire terrain up/down.

Adding the snow object seems to reveal a graphical issue.

This snow movement bug works outside snow as well. Where terrabrush node tries to move instead of other nodes I try to move. To fix this bug, I have to click terrabrush, then click off it, and if this doesn't work I click update terrain so I can try moving other nodes again.
[display_bug-Trim.webm](https://github.com/spimort/TerraBrush/assets/157936534/9a950d25-6e74-40fd-9aff-53295f175620)

**Comment by Ika-BakaKu** [comment]
I noticed this issue happens outside having snow added. So this bug is not related to snow, it's happened when I try to move player or nodes outside terrabrush

**Comment by spimort** [comment]
Hey @Ika-BakaKu , can you confirm it still happens with the newer versions?

**Comment by Ika-BakaKu** [comment]
So far haven't seen the issue. If I break it any other way, I'll make a new post 😄
