### ISSUE TITLE
Height Textures not changing anything

### ISSUE THREAD

**Issue by teezytoldme** [spimort/TerraBrush#157]
Love the plugin so far. However when I put a height texture for the in the texture sets, it doesnt seem to make any visible changes regardless of what number I put as the height blend factor.

I've used textures downloaded from ambientcg and used the displacement file for the height. Everything is set as default and I've also used the same textures sets on a standard plane mesh with a standard material shader and they seemed to work just fine.

Am I doing something wrong?

Thankyou.

**Comment by spimort** [comment]
Hey @teezytoldme !
Thanks, I'm glad you enjoy it!

Right now, the height texture is used to determine how textures will blend together.

For example, a blending value of 10 would make my brick texture pop : 
![image](https://github.com/user-attachments/assets/e3bc9c25-f466-49c6-bcbf-85d2710a68b2)

a blending value of 0 would make my brick texture almost invisible : 
![image](https://github.com/user-attachments/assets/9a5df5e7-0097-492d-b5b5-313ce6a4c9a5)

So the height helps to decide which texture to use depdending on the height of each.

I hope this helps!

**Comment by teezytoldme** [comment]
thanks alot makes sense.

**Comment by spimort** [comment]
Sounds good! I'll close this issue, feel free to ask more questions in other issues 🙂
