### ISSUE TITLE
[Bug] Adding foliage Resources with Multi Mesh generates unwanted initial mesh causing lag and crash

### ISSUE THREAD

**Issue by superhighlevel** [spimort/TerraBrush#160]
Godot Version: v4.3.stable.mono.official [77dcf97d8]
System Info: Godot v4.3.stable.mono - Windows 10.0.26100 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6094) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

Problems:

When adding a new FoliageResource with a Random mesh and a MultiMesh strategy, clicking Update Terrain generates an unknown amount of plane mesh at the center. This causes lag and can cause the editor to crash.
![Godot_v4 3-stable_mono_win64_i2YruoeoSf](https://github.com/user-attachments/assets/35fdccb3-7877-4669-b5d2-0b2fd4bde734)

Steps to reproduce:
1. Create a new project in mono and install TerraBrush in AssetLib
2. Create a new 3D Scene, add a new TerraBrush Node, and click CreateTerrain in TerraBrush Node
3. Create new Foliages with everything in default, add a new Box Mesh, and click Update Terrain

Minimal reproduction project (MRP):
[terrabrush.zip](https://github.com/user-attachments/files/17540501/terrabrush.zip)

**Comment by spimort** [comment]
Hey @superhighlevel ! Thanks for the reproduction, I'll have to check that!
I think this is the samething as this one, right?

https://github.com/spimort/TerraBrush/issues/158

**Comment by spimort** [comment]
@superhighlevel It should be fixed with the version 0.9.3Alpha.
Let me know if it works! 🙂

I'll close the issue for now, we can reopen it if needed.
