### ISSUE TITLE
Request: A brush setting that sets terrain to 1 height

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#17]
Making a 2.5D game is fun, but often the pixel designs require more square and flat terrain. The current flat and smooth brushes are great, but lack a way to set a terrain to a certain height.

I'd love the + / - brushes having a setting to lock height to a certain amount. Where maybe 0 is the terrains starting height, then set the amount of height to 5 to make smooth cliffs, but if I mess up I can easily set back to 0 to get back to the flat starting terrain.

If typical users don't need this, maybe make it a check setting above the terrain editor tools tab that says, lock height, then enter height amount.

**Comment by spimort** [comment]
This should be part of the main branch now, please, let me know if it fits your needs 🙂

**Comment by Ika-BakaKu** [comment]
TY so much, I'll try to break it soon

**Comment by spimort** [comment]
Awesome 😁 I'll close it for now
