### ISSUE TITLE
Not able to activate in Godot 4.3

### ISSUE THREAD

**Issue by ljlhouben** [spimort/TerraBrush#172]
![image](https://github.com/user-attachments/assets/a2c1c780-f6da-4e99-a107-e0040d82bc73)
I'm trying to install TerraBrush in order to test it for my project. However I get an error on activating it in the project environment (see attachment). I created a new and empty project in Godot 4.3 stable, downloaded it via the asset library. It downloaded and installed without error. I also reloaded the complete project, but the issue exists. 
![image](https://github.com/user-attachments/assets/12cbf912-f336-4b68-bc13-42f092a92337)

**Comment by spimort** [comment]
Hey @ljlhouben !

Make sure you use the .net version of Godot since this is a C# plugin.
Also, make sure you build the solution before to enable the plugin.

Let me know if it works! 🙂

**Comment by spimort** [comment]
I'll assume it works on your side, feel free to reopen the issue if needed 🙂

**Comment by Cat-Lips** [comment]
For me, the issue was that the pre-built libs were not included in the asset package.
However, I was able to download them separately and add them to the addons folder.

Love your work, spimort!

**Comment by spimort** [comment]
Good to know @Cat-Lips ! It's strange that it was not included tho, I'll try to check that!

I'm glad you enjoy it 🙂
