### ISSUE TITLE
Brush Bug: Brush icon bugs out or vanishes

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#26]
When hitting update, the brush settings are saved, but the tool icons are not, which  bugs out the brush display and sometimes even makes it disappear.

![what](https://github.com/spimort/TerraBrush/assets/157936534/f62319b9-12fd-40a3-997b-22673b24fa80)

![what2](https://github.com/spimort/TerraBrush/assets/157936534/11624483-357e-4c93-a37a-f9e8ad21f8a3)

Spam clicking brush icons can break this further, not sure if this is related to brush vanishing or not 🤔 

Note: The brush doing this seems to have 0 effect on it's ability to paint, unless it vanishes, then any terrain painting doesn't show up either, but it will state in the output: "modifies terrain"

**Comment by spimort** [comment]
Is this still happening after I fixed the brush "sync" selection?

**Comment by Ika-BakaKu** [comment]
This seems to be fixed with latest version, if anything happens again I'll report a new report
