### ISSUE TITLE
Report: Height display is not accurate

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#35]
Where I clicked in the photo was height 0, if I ctrl+click randomly on height 0 terrain, it will display different numbers

![not_right](https://github.com/spimort/TerraBrush/assets/157936534/0ab208f6-d3ae-4779-a171-198263643137)

**Comment by spimort** [comment]
Do you still have this issue? I was not able to reproduce it on my side 🙂

**Comment by Ika-BakaKu** [comment]
Fixed, TY
