### ISSUE TITLE
Request: foliage wind option for wind direction

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#36]
Love wind, it's amazing, however my 2.5D game uses a lot of billboards and objects that only appear in a single direction. I noticed wind makes these objects sway up and down, rather than the direction I need it to run.

Probably only an issue for me, but hope my request is considered one day 😸 Thank you

**Comment by spimort** [comment]
In the version 0.3.9Alpha, I changed the Material for the foliage so you can put shaders.
This allows you to simulate something like wind (here's a basic example in a shader) : 
![image](https://github.com/spimort/TerraBrush/assets/6035485/27d6f931-fe51-41d9-bc20-e0b6ba149ea1)

Also, here's a sample video of it : 

https://github.com/spimort/TerraBrush/assets/6035485/6453e694-7fa3-4fb6-9e6b-1b8a8ff4d46d

Please, let me know if it fits your need

**Comment by spimort** [comment]
This should have fix the issue
