### ISSUE TITLE
SpotLight3D Reflection

### ISSUE THREAD

**Issue by pdsfilho** [spimort/TerraBrush#40]
Hello! I probably encountered a bug using a SpotLight3D for my character. Half the map detects the light, but the other half doesn't. 
The SpotLight3D is placed under the character camera and works as intended with others default godot levels.

Screenshots attached:
https://imgur.com/a/xdRYmSi

Best Regards.

**Comment by spimort** [comment]
Interesting! I'll try to reproduce it on my side 🙂!

**Comment by pdsfilho** [comment]
I found someone in godot forums with a similar problem, it looks like is something about "Ensure Tangents". 

Maybe this would interest you :thumbsup: 
https://godotforums.org/d/39357-strange-shadowing-with-omnilight3d-on-planar-surfaces-possible-bug/6

Btw, your plugin is awesome!

**Comment by spimort** [comment]
@pdsfilho super interesting! I'll check the link this week 🙂

I'm glad you like the plugin 😎

**Comment by spimort** [comment]
hey @pdsfilho ! 
I tried to reproduce the situation on my side but I was not able to 🫤

![image](https://github.com/spimort/TerraBrush/assets/6035485/38b3959d-256a-4ed4-98ee-1530aeac4677)

Would you be able to create a sample project for me?
Also, if needed, I have a discord server where we could talk : https://discord.gg/htktb7k

**Comment by pdsfilho** [comment]
Hello! 
I've created a new project but the problem persists, unfortunately :sweat: . It has a camera and a SpotLight (both pointed to the ground)
<img width="957" alt="TerraBrush1" src="https://github.com/spimort/TerraBrush/assets/8051184/cee7f1c5-a55f-41fe-bce4-3aca9c1f6f7f">

I am using an integrated video card for intel processor. I don't know if could be relevant, but anyway, thanks for helping me and for your time!
I will try to get into discord as soon as possible.

This is the repository for the test project:
https://github.com/pdsfilho/TerraBrush_Test

**Comment by spimort** [comment]
Hey, thank you for the project, It was also happening to me in your project.
Tho, I updated TerraBrush in your project and it fixed the issue.

Could you try it again on your side to see if the last update fixes your issue?

**Comment by pdsfilho** [comment]
It worked nicely! Thanks!

Oh, and I just left a gift for ya :sunglasses:

**Comment by spimort** [comment]
@pdsfilho That's perfect! I'll close the issue then !

And thank you for the gift, that's crazy cool! 😎
