### ISSUE TITLE
Request - different trail options for snow feature. 

### ISSUE THREAD

**Issue by Schwagsone** [spimort/TerraBrush#42]
Right now the options seems to be a block that cuts into the snow - which is probably the best option for most games tbh. Would be nice for a round or smooth option or even an option to size the trail. Not sure how hard or possible this is but would be a fun option in the plugin to sort of create your own trail with some variables or even a couple static options you can click.

**Comment by spimort** [comment]
It's not a trail option but the snow compression has now been improved in 0.3.11Alpha. 
It should cover most of the situations.

I'll close the issue.
