### ISSUE TITLE
Object collider errors

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#46]
I started adding my custom object scenes into terrabrush, when I noticed massive spam starting to happen. (see image)

The errors spam the editor and while playing, but if I remove all the objects from the terrain, the errors stop.

I'm not sure if this is because of me having breakable objects that use area3D and collisionshape3D / collisionpoly3D or what.

I will be testing which objects are causing this issue, but at the moment, seems all object scenes I use that have colliders are causing this error spam. (see bottom image on barrel object scene)

![colliders](https://github.com/spimort/TerraBrush/assets/157936534/e7465aea-76ab-4842-aaee-d243d87bf867)

![object](https://github.com/spimort/TerraBrush/assets/157936534/25f3e606-854b-441e-8817-3e1db35d3e12)

**Comment by sellenth** [comment]
I've also been getting this error. just removed collisions on those objects for now...

**Comment by spimort** [comment]
Sounds good, I think I know what the issue is, I'll check it 🙂

**Comment by spimort** [comment]
@Ika-BakaKu @sellenth The version 0.3.8Alpha should fix the issue
