### ISSUE TITLE
Request: Water Shader support

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#47]
I use custom water shaders, and would LOVE shader support to the water brush. I bet it could be better on resources if it was all in the terrabrush than node spams.

I use visual shaders more than basic shaders, so this may be a huge request, but it would be amazing to see one day :D
![water_shader](https://github.com/spimort/TerraBrush/assets/157936534/e8ad9e09-7bc7-499a-80c8-2306b7699c6e)

**Comment by spimort** [comment]
This is now supported with the version 0.3.10Alpha
