### ISSUE TITLE
Request: Pit Brushes | Erase Terrain (Making Pit holes)

### ISSUE THREAD

**Issue by Ika-BakaKu** [spimort/TerraBrush#48]
I'd like to request a brush that erases terrain, while also forming nearby terrain into a fall pit, or falling zones.

Similar to the water brush, but no water.

My game has a lot of darkness and fall zones, thus having full terrain feels a waste if you mostly walk on some raised terrain.

Only thing to remember is, if you fall, the terrain has to have edges that look like the cliffs drop down, not just massive holes.

This 2D version is for reference, to understand what I mean by falling, but the terrain drops down still. (My words suck, I'm an artist)
![preview](https://github.com/spimort/TerraBrush/assets/157936534/414d717c-156d-46a9-b690-8c5f96a8aefb)

Full 2D video if you want more to go on than a low res photo.
https://www.youtube.com/watch?v=pSj8m3PlfdQ

**Comment by spimort** [comment]
This is now available in version 0.5.0Alpha 🙂
