### ISSUE TITLE
Lack of Lods.

### ISSUE THREAD

**Issue by Saul2022** [spimort/TerraBrush#5]
The terrain is well feature packed, but it lacks any kind of lods system which gives the terrain a bad performance.For example this terrain is 1024 of size and tanks performance on a igpu.

![editor_screenshot_2023-12-23T112151](https://github.com/spimort/TerraBrush/assets/97898580/f7316056-a9cd-4b47-8bbd-14997b4cb771)

**Comment by spimort** [comment]
Thanks for posting this issue!

For my own project, having a big map was not a requirement that's why there is no LOD at the moment. I'll check if I can add the support of something like clipmaps (probably after the holidays).

**Comment by Saul2022** [comment]
> For my own project, having a big map was not a requirement that's why there is no LOD at the moment. 

That alright though  i think lods would still be needed  for lower end gpus that can't handle terrain, like even at 254 the fps were slow for an igpu. You could also try the method cory used for his terrain called geoclipmap, though it may not be what you're looking for https://github.com/TokisanGames/Terrain3D

**Comment by spimort** [comment]
@Saul2022 
The clipmap LOD feature has been merged into main, if you want to try it!
Also with a devlog about it : https://youtu.be/BardvKC0HF0

**Comment by spimort** [comment]
I'll close the issue. If needed, feel free to open a new one about this!
