### ISSUE TITLE
Request for tooltips

### ISSUE THREAD

**Issue by Flynsarmy** [spimort/TerraBrush#57]
When using this addon for the first time, there are a lot of icons and I don't know what any of them do:
![image](https://github.com/spimort/TerraBrush/assets/334808/b2a724dc-52f7-4329-b5e1-9661f0cf8c31)
It would be great if I could hover my house over them to get a description of what they do.

This also applies to the V key. When pressing V and moving around the circle, could the center text update to the name of the tool I'm currently hovering?
![image](https://github.com/spimort/TerraBrush/assets/334808/9bbe8e08-c686-4e2b-a387-faed5b5b98c4)
Sidenote: That text is very hard to read. It needs its colors fixed.

**Comment by spimort** [comment]
@Flynsarmy Sounds good, I'll check to add Tooltips!

**Comment by spimort** [comment]
@Flynsarmy that should be included in version 0.3.13Alpha. Let me know if it works for you!

**Comment by spimort** [comment]
I'll close this issue, if any problem make sure to open a new one 🙂

**Comment by Flynsarmy** [comment]
Hey sorry for the late reply it was easter weekend here in AU.
The G and H keys are still hard to read:
![image](https://github.com/spimort/TerraBrush/assets/334808/d1ee8dad-6cdc-4cc5-8ff5-5777fe858300)
![image](https://github.com/spimort/TerraBrush/assets/334808/a06c7037-d65f-4de8-a7d9-2ae2b3f9e633)

V key is wonderful now! The only issue I still have with it is that you need to hover and wait over every icon to get the tooltip:
![image](https://github.com/spimort/TerraBrush/assets/334808/66947b95-41d6-42bd-a678-43bd08757226)
I'd much prefer the word 'Tools' in the center changes to 'Tools - Flatten Terrain', 'Tools - Lower Terrain' etc as you mouse move over each tool. Much faster to visually parse and also gives a bit more use to the Tools label.

**Comment by spimort** [comment]
Oh sorry I closed it too early, I'll open it again! I thought that your reaction was the confirmation, sorry about that haha!

I'll improve the G/H menu, no problem 🙂

For the V menu, you are missing something, just make sure you recompile the project after upgrading. The V menu should have the name of the tool in the label as well.

Could you recompile with the hammer button and confirm me it's there?

I'll check the other stuff later.

**Comment by Flynsarmy** [comment]
Oh my bad, I've never worked with a C# project before, didn't know I needed to rebuild after the plugin update. 

Absolutely perfect! This is such an improvement! The little opening animation is great too.
![image](https://github.com/spimort/TerraBrush/assets/334808/e9c8d1fe-b24b-4639-a03f-08e5fd2fbad4)

**Comment by spimort** [comment]
hey @Flynsarmy ! Version 0.4.0Alpha is out and I think it should fix this issue, let me know 🙂!

**Comment by Flynsarmy** [comment]
Looks nice. The UI with G and H keys is now fixed. My last remaining issues are:
1. There is a lack of clarity on which icon is currently highlighted. When I hover my mouse over an icon, its background changes slightly lighter but it's still hard to tell which is the currently selected, and which is the newly highlighted icon. Both should have a brighter background.
2. Should pressing the V, B, G, H keys while the modals are already open close them? Feels weird to just pop the same modal up again. At the moment you need to reach all the way up to the escape key or right click to close the modal.

Both issues are demonstrated in the video below:
https://github.com/spimort/TerraBrush/assets/334808/0b26cf21-21f0-4d51-9db0-a6822f463f75

**Comment by spimort** [comment]
@Flynsarmy alright, I'll check what I can do!

**Comment by spimort** [comment]
Hey @Flynsarmy , could you try this branch, so I don't release a new version without it working 🙂 ?
https://github.com/spimort/TerraBrush/tree/fix/improve-pie-ux

**Comment by Flynsarmy** [comment]
Sure thing. I'll take a look in the morning (it's midnight here in AU)

**Comment by Flynsarmy** [comment]
Much better and a massive improvement from where we started! Thanks for your work on this!

**Comment by spimort** [comment]
Perfect! I'll merge the PR then!
