### ISSUE TITLE
An error terrabrush throws to my console in godot at startup. (Does not seem to affect usage)

### ISSUE THREAD

**Issue by TheRealFame** [spimort/TerraBrush#6]
This is with godot 4.2.1 stable mono installed. It seems to only happen when on a scene without the terrabrush node 

` /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.NullReferenceException: Object reference not set to an instance of an object.
     at TerraBrush.Terrain.BuildTerrain(Boolean collisionOnly) in M:\GodotGames\(GameName)\addons\terrabrush\Scripts\Terrain.cs:line 46
     at TerraBrush.TerraBrush.LoadTerrain() in M:\GodotGames\(GameName)\addons\terrabrush\TerraBrush.cs:line 316
     at TerraBrush.TerraBrush._Ready() in M:\GodotGames\(GameName)\addons\terrabrush\TerraBrush.cs:line 193
     at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
     at Godot.GodotSynchronizationContext.ExecutePendingContinuations() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotSynchronizationContext.cs:line 51
     at Godot.GodotTaskScheduler.Activate() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotTaskScheduler.cs:line 76
     at Godot.Bridge.ScriptManagerBridge.FrameCallback() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs`

**Comment by spimort** [comment]
Thanks, I'll check it out 🙂!

**Comment by TheRealFame** [comment]
![image](https://github.com/spimort/TerraBrush/assets/29516927/73173cea-86b6-4e3e-8c79-69474144b858)

CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. M:\GodotGames\(Game Name)\addons\terrabrush\TerraBrush.cs(787,35)

CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. M:\GodotGames\(Game Name)\addons\terrabrush\Scripts\TerrainPositionInformation.cs(6,56)


CS8618: Non-nullable field '_keyDisplay' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. M:\GodotGames\(Game Name)\addons\terrabrush\Scripts\KeyListenDialog.cs(14,27)

CS8618: Non-nullable field '_okButton' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. M:\GodotGames\(Game Name)\addons\terrabrush\Scripts\KeyListenDialog.cs(15,28)

CS8618: Non-nullable field '_cancelButton' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. M:\GodotGames\(Game Name)\addons\terrabrush\Scripts\KeyListenDialog.cs(16,28)

**Comment by TheRealFame** [comment]
Heres some more debug! Updated to 4.3.2 but this is the the error from the build i also got on 4.2.2 stable.

**Comment by spimort** [comment]
@TheRealFame 
I'll check for the warnings.
Can you test the new version available, I think it should fix your first issue 🙂

**Comment by TheRealFame** [comment]
> @TheRealFame I'll check for the warnings. Can you test the new version available, I think it should fix your first issue 🙂

Same thing sadly 😅, Sorry i took so long but there's these errors here below

**Comment by TheRealFame** [comment]
![image](https://github.com/spimort/TerraBrush/assets/29516927/9d2030cc-f59f-462e-b576-44be6bdbb455)

![image](https://github.com/spimort/TerraBrush/assets/29516927/3b1a3b04-0572-44f8-93c4-4c801667e929)

**Comment by spimort** [comment]
No worries, there is no rush!
Well these are warnings that I'll check to remove but I was more talking about the initial errors you had.
The `NullReferenceException`.

**Comment by TheRealFame** [comment]
> No worries, there is no rush! Well these are warnings that I'll check to remove but I was more talking about the initial errors you had. The `NullReferenceException`.

Oh? The one's i started the issue with.. I don't seem to be getting them, So it may of been fixed. Although i'm not doing anything like running the map or scene so i don't know if the error is fully gone.

**Comment by TheRealFame** [comment]
![image](https://github.com/spimort/TerraBrush/assets/29516927/cb6637db-316d-4a4a-ae59-f2bbfad0b141)

Welp, I started getting these errors after adding my grass and concreate texture in. Both of them being png's... Ugh, I'll remake the node

**Comment by TheRealFame** [comment]
It worked- I imported both textures at first.. But importing one texture seems to work!

![image](https://github.com/spimort/TerraBrush/assets/29516927/0784388a-a1f6-40e2-99ca-f003833e0d1c)

**Comment by TheRealFame** [comment]
Oh. I figured out the road file somehow conflicts with the addon and just doesn't work..

**Comment by TheRealFame** [comment]
Sorry for spamming this one thread about my findings- But sorry. The file was above 2000 by 2000 😅

**Comment by spimort** [comment]
> > No worries, there is no rush! Well these are warnings that I'll check to remove but I was more talking about the initial errors you had. The `NullReferenceException`.
> 
> Oh? The one's i started the issue with.. I don't seem to be getting them, So it may of been fixed. Although i'm not doing anything like running the map or scene so i don't know if the error is fully gone.

Perfect, feel free to post again about an issue if you have anything about the null reference.
I think I'll open a seperate one for the warnings.



> It worked- I imported both textures at first.. But importing one texture seems to work!
> 
> ![image](https://private-user-images.githubusercontent.com/29516927/297232641-0784388a-a1f6-40e2-99ca-f003833e0d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTUyMzQsIm5iZiI6MTcwNTQ1NDkzNCwicGF0aCI6Ii8yOTUxNjkyNy8yOTcyMzI2NDEtMDc4NDM4OGEtYTFmNi00MGUyLTk5Y2EtZjAwMzgzM2UwZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxMjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOGUxMTFhNzYwNzhmNzlmZjI3ZDEwNzhhMTE5MGIyNzU2MDQ1OWQwYjA2MmFlYzNjMGIwYWY0NjAyYjhhMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i07M4SlwAlZmI5bCfzhSLP6VfWId21cRraIt9OmUYvE)

Make sure all of your textures uses the exact same format (Compression, Clipmap, etc.). This is very easy to mess this up sadly, Godot loves to change the format of the files some times!

> Sorry for spamming this one thread about my findings- But sorry. The file was above 2000 by 2000 😅

No worries! I'm really happy to help you with that :)
If you want, I also have a discord server :)

https://discord.gg/QPkm6cKmq4
