### ISSUE TITLE
Disable Texture Filtering

### ISSUE THREAD

**Issue by violetfrost** [spimort/TerraBrush#60]
Hi,

I'm working on a PSX style game, and as such texture filtering goes against the art style. However, this seems to use it by default. Is there any way to turn it off, or are you considering adding such a thing?

**Comment by violetfrost** [comment]
I managed to do this by changing the sampling in `heightmap_clipmap_shader.gdshader`, but I'd love to see an officially supported toggle for it if possible.

**Comment by spimort** [comment]
Hey @violetfrost !

I'll see what I can do about this. Shaders are complicated because the filter part can not be dynamic (or injected by a script).
I think I'll have to create a new shader while building the terrain so we can have that setting has "dynamic".

**Comment by spimort** [comment]
Hey @violetfrost !
The version 0.3.16Alpha should now include a way to switch to nearest filter !
Let me know if it fits your needs.

Linear
![image](https://github.com/spimort/TerraBrush/assets/6035485/996781c9-3ba7-462e-a906-ef98de55808d)

Nearest
![image](https://github.com/spimort/TerraBrush/assets/6035485/7fa11f80-792e-4a71-96c8-bd374b5dcd8d)

**Comment by spimort** [comment]
I'll close the issue for now, if you find something else, let me know!
