### ISSUE TITLE
Loading the terrain and loading objects when launching a project.

### ISSUE THREAD

**Issue by HitARun** [spimort/TerraBrush#66]
Now the terrain is loaded first and you can see how the objects is loaded. Despite the fact that it speeds up loading in general, for the user, most often the appearance of objects in front of the eyes is a more negative experience than a long wait for the entire scene to load at once.
Solutions: add a loading method switch or change the scene loading method when compiling the project.

**Comment by spimort** [comment]
Hey @HitARun , this feature is now available in version 0.4.5Alpha. I'll close this issue for now, if you find something, let me know, I'll reopen it!
