### ISSUE TITLE
Scaling of textures

### ISSUE THREAD

**Issue by HungryCatGames** [spimort/TerraBrush#68]
Some textures work fine, however others need to be scaled down (or up) to fit into the scale of the world. Can there be an option in each texture definition to scale it?

**Comment by spimort** [comment]
@HungryCatGames Some stuff will have to change to support that but this is definitely doable. I'll flag it as improvement 🙂

**Comment by spimort** [comment]
This feature should now be part of the version 0.4.3Alpha 🙂

I'll close the issue for now, if you find something else, let me know!

**Comment by HungryCatGames** [comment]
Thanks! 
But... I copied the (current) 0.4.5 alpha files into my addons and started the project and got a bunch of errors. I tried a build and it failed to build. Disabled the plugin and tried a build and same issue. Can I not just drag in a new version? I can post the errors if you'd like.

**Comment by spimort** [comment]
Usually the way it works is that you should remove your current folder for the addon. And then, you copy the new folder into you addon folder.

The next step will always be to recompile using the hammer button.

Also, some people told me that sometimes, Godot like to change the language of the addon to GDscript inside of the plugin edit dialog. Make sure it's still to C# : 
![image](https://github.com/spimort/TerraBrush/assets/6035485/438a43b7-0f86-409a-94c0-c485e65963d0)

If it does not work, yes please, post the error 🙂
