### ISSUE TITLE
Add an UV scale for the textures

### ISSUE THREAD

**Issue by Vacation02** [spimort/TerraBrush#69]
Add an UV scale for the textures so you can make them smaller or bigger

**Comment by spimort** [comment]
Hey @Vacation02 ! I think this would be a duplice of this, right?
https://github.com/spimort/TerraBrush/issues/68

If so, I'll close this one so we keep only one.

**Comment by Vacation02** [comment]
> Hey @Vacation02 ! I think this would be a duplice of this, right? #68
> 
> If so, I'll close this one so we keep only one.

yea
