### ISSUE TITLE
Request: Add a set height input field

### ISSUE THREAD

**Issue by Schwagsone** [spimort/TerraBrush#73]
I noticed the set height gets reset if you switch out the tool. Would be nice for me personally to be able to type in the height, instead of mouse wheeling or even if easier to implement it saves the height from the last height set.

**Comment by spimort** [comment]
This should now be available in version 0.4.4Alpha.

When you select your "Set height tool", you can press "N" to open a dialog that let you set the height.
The height should also remain even if you change the tool.

Let me know if it works for you!

**Comment by Schwagsone** [comment]
looks good to me, thx!!!
