### ISSUE TITLE
Request: Allow us to reduce the initial grid.

### ISSUE THREAD

**Issue by MihaSmit** [spimort/TerraBrush#86]
I don't need excessive detail in the first chunk, how can I increase the mesh size?
![изображение](https://github.com/spimort/TerraBrush/assets/16068635/4c1985a2-512c-4f02-b8da-b3a90e07f450)

**Comment by spimort** [comment]
I think you found it by yourself, but just to complete the question, under the LOD section, the "initial cell width" will control how big is the "smallest" cell.

For example, a value of 1 would mean that your smallest cell is 1m : 
![image](https://github.com/spimort/TerraBrush/assets/6035485/e8caaabb-5f48-4e9d-b876-131de4d7e21a)

And a value of 3 would mean that your smallest cell is 3m : 
![image](https://github.com/spimort/TerraBrush/assets/6035485/db60f63c-9b14-43d7-bc08-5c6923b6f375)

I hope this helps! 🙂
