### ISSUE TITLE
The plugins has C# warnings

### ISSUE THREAD

**Issue by spimort** [spimort/TerraBrush#9]
![image](https://github.com/spimort/TerraBrush/assets/29516927/9d2030cc-f59f-462e-b576-44be6bdbb455)

![image](https://github.com/spimort/TerraBrush/assets/29516927/3b1a3b04-0572-44f8-93c4-4c801667e929)

_Originally posted by @TheRealFame in https://github.com/spimort/TerraBrush/issues/6#issuecomment-1894755186_

**Comment by DriftWare07** [comment]
I also have a few issues. Sometimes when i try to add textures, the whole terrain just turns shiny black and i get these errors.
![image](https://github.com/spimort/TerraBrush/assets/99690970/fe53f39c-77b6-4ab0-b075-1319dd382ed6)

**Comment by DriftWare07** [comment]
I also get this:
![image](https://github.com/spimort/TerraBrush/assets/99690970/27d5d3e6-ca6e-40ba-ab37-ef6bf3f6a88f)

**Comment by spimort** [comment]
@DriftWare07 
Humm, are you in the main branch?

**Comment by DriftWare07** [comment]
I downloaded the scene from the main branch, and copied the addon to my own project.

**Comment by DriftWare07** [comment]
I'm using 4.2.1 mono

**Comment by spimort** [comment]
Ok sounds good, I thought that maybe you were using my wip branch for the multizones.

So, did you provide all the textures (Albedo, normals, roughness)?
If so, make sure that all of your textures are in the exact same format while importing them. So, they all need to have the same Compression mode, mipmaps, everything : 
![image](https://github.com/spimort/TerraBrush/assets/6035485/a28e9db5-ed58-46a1-b3c7-b9bbd4991bad)

**Comment by DriftWare07** [comment]
So for my textures, i only have albedos

**Comment by DriftWare07** [comment]
Do i absolutely have to have normal or roughness maps?

**Comment by spimort** [comment]
Right now the plugins works in a way that all the textures need to be provided. If you don't have those textures, you can create for example, all black or all white image for the roughness and all "purple" for the normals (like in this website, with a strength of ~0, https://cpetry.github.io/NormalMap-Online/).

**Comment by DriftWare07** [comment]
Ok, will do

**Comment by spimort** [comment]
Sounds good, let me know if it works 🙂

**Comment by DriftWare07** [comment]
I replaced the roughness maps with completely rough (white) textures but it's still pretty shiny

**Comment by spimort** [comment]
Are you able to provide a sample project? 
Or a screenshot with the settings?

It would be easier to investigate.

**Comment by spimort** [comment]
Most of them are now fixed. Some intended ones remains, until the obsolete properties are gone : 
`This property was there before the zones were a thing, will be removed in the future`
