### ISSUE TITLE
Object frequency when using object painting image in zones

### ISSUE THREAD

**Issue by niklasking** [spimort/TerraBrush#94]
When painting the terrain with the brush, it is possible to configure the object frequency, so that you can separate for instance trees the way you like.
When using object painting images for zones, this is not possible. Instead, the objects are placed very, very close to each other, which is not ideal when modeling a forest.
It would be good to have the same behavior for zones as for painting with the brush.

**Comment by spimort** [comment]
Hey @niklasking !

Is this what you mean?
![image](https://github.com/spimort/TerraBrush/assets/6035485/f6132577-e4ac-4eb4-8729-da853d72aed3)

This allows you to reduce/increase the frequency of the objects when you paint 🙂
The -1 you see here means that you will use the deault. If you increase it, higher than -1, this is the one that will get applied.

Let me know if this is what you mean!

**Comment by niklasking** [comment]
Exactly, this is what I want, but you said earlier that it does not work when using images in the zones.
So if you make this to work even when using my own images in the zones that would be perfect!

**Comment by spimort** [comment]
Oh yeah, I mean what you mean, in your case, you are not using the paint tool but an image!
I'll check what I can do about this 🙂

**Comment by niklasking** [comment]
Thanks a lot!

**Comment by spimort** [comment]
This should work now with the version 0.9.0Alpha 🙂
I'll close the issue, feel free to open a new one if needed!
