### ISSUE TITLE
Black terrain when adding textures

### ISSUE THREAD

**Issue by HEofOttoman** [spimort/TerraBrush#98]
![image](https://github.com/spimort/TerraBrush/assets/145900606/0a148019-dde1-4f3b-9e4a-d507a04925c8)
_I was just trying to give water noise textures when this happened. Removing the noise textures didn't help, but I had to remove and re-add every texture I had._
Godot 4.2.2
Terrabrush 0.6.1 
Edit: The cause is having 2 textures at once, not water

**Comment by HEofOttoman** [comment]
upon further testing, when I tried to add normal textures to the water again, it worked.

**Comment by spimort** [comment]
Hey @HEofOttoman !

This is due to the fact that not all of your textures share the same format (this is required by the shader).

The thing you should check is the compress mode and the mipmap generation.
Right now you should have an error in the console saying you this.

Also, as soon as you put for example a normal texture, make sure you provide one for all the texture sets.

I talk about this in this video (at about this time) : https://youtu.be/n5WeAqeea1c?t=271

Let me know if it helps 🙂

**Comment by HEofOttoman** [comment]
oh ok thank you. Does it have to be the same file format (ie. all .png or .jpg) because 
![image](https://github.com/spimort/TerraBrush/assets/145900606/38ea3332-c9e9-44d4-930c-48b288d185fb)
this happened after I fixed all the settings

**Comment by HEofOttoman** [comment]
Removing the other materials didn't remove the issue either,
![image](https://github.com/spimort/TerraBrush/assets/145900606/218ca12c-b0c1-47bd-9275-dc00cd4310b6)

**Comment by HEofOttoman** [comment]
reloading the scene only removed the black parts, but turned everything grainy.
![image](https://github.com/spimort/TerraBrush/assets/145900606/8b8601f2-2390-459f-a67c-8d0c829651a3)

**Comment by HEofOttoman** [comment]
I tried to change the compression, but Godot wouldn't let me change it at all

**Comment by Schwagsone** [comment]
Join discord and can help quicker if you like. Textures need to be of same file and look like this to my knowledge. 
![image](https://github.com/spimort/TerraBrush/assets/116524236/1046de99-f2b5-4acb-a268-65840109a366)

**Comment by HEofOttoman** [comment]
Thank you for helping. However, after closing godot and trying again 15 hours later, the issue had disappeared, and all the textures, upon being re-added were working again, even though some of the files have different formats.

**Comment by spimort** [comment]
Alright, cool! So, I can close this issue for now 🙂?
You can always open another one if needed later!

**Comment by HEofOttoman** [comment]
I will, but one more question
![image](https://github.com/spimort/TerraBrush/assets/145900606/74e3b5af-1f46-4413-a03b-d6f98170613f)
is there a way to fix these artifacts?

**Comment by HEofOttoman** [comment]
Once again, thank you very much. This is a very good plugin.

**Comment by spimort** [comment]
Sounds good, I'm glad you like it! 🙂
